import {
  FaClipboardList,
  FaCalendarAlt,
  FaUserMd,
  FaFilePrescription,
  FaBookOpen,
  FaGamepad,
  FaHandsHelping,
  FaUser, 
  FaHome,
  FaSignOutAlt,
  FaClock,
  FaMoneyBillWave,
  FaUsers,
  FaUserShield,
  FaChartBar,
  FaCogs,
  FaCheckCircle,
  FaUpload,
  FaMoneyCheckAlt,
  FaComments,
} from "react-icons/fa";

export const patientMenuItems = [
  { title: "হোম", link: "/dashboardPatient", icon: <FaHome /> },
  { title: "অ্যাসেসমেন্ট", link: "/dashboardPatient/assessment", icon: <FaClipboardList /> },
  { title: "অ্যাপয়েন্টমেন্ট", link: "/dashboardPatient/appointment", icon: <FaCalendarAlt /> },
  // { title: "বুকিংস", link: "/dashboardPatient/bookings", icon: <FaCalendarAlt /> },
  { title: "ডাক্তার", link: "/dashboardPatient/doctorList", icon: <FaUserMd /> },
  { title: "প্রেসক্রিপশন", link: "/dashboardPatient/prescription", icon: <FaFilePrescription /> },
  { title: "রিসোর্স", link: "/dashboardPatient/resources", icon: <FaBookOpen /> },
  { title: "গেমস", link: "/dashboardPatient/games", icon: <FaGamepad /> },
  { title: "সাহায্য", link: "/dashboardPatient/patientHelp", icon: <FaHandsHelping /> },
  { title: "প্রোফাইল", link: "/dashboardPatient/patientProfile", icon: <FaUser /> },
  { title: "লগ আউট", link: "/", icon: <FaSignOutAlt /> ,isLogout: true},
];

export const doctorMenuItems = [
  { title: "হোম", link: "/dashboardDoctor", icon: <FaHome /> },
  { title: "অ্যাপয়েন্টমেন্ট", link: "/dashboardDoctor/appointment", icon: <FaCalendarAlt /> },
  { title: "শিডিউল", link: "/dashboardDoctor/schedule", icon: <FaClock /> },
  { title: "ইনকাম", link: "/dashboardDoctor/income", icon: <FaMoneyBillWave /> },
  { title: "সাহায্য", link: "/dashboardDoctor/doctorHelp", icon: <FaHandsHelping /> },
  { title: "প্রোফাইল", link: "/dashboardDoctor/doctorProfile", icon: <FaUser /> },
  { title: "লগ আউট", link: "/", icon: <FaSignOutAlt /> ,isLogout: true},
];

export const adminMenuItems = [
  { title: "হোম", link: "/dashboardAdmin", icon: <FaHome /> },
  { title: "পেশেন্ট ম্যানেজমেন্ট", link: "/dashboardAdmin/users", icon: <FaUsers /> },
  { title: "ডাক্তার ম্যানেজমেন্ট", link: "/dashboardAdmin/doctors", icon: <FaUserMd /> },
  { title: "অ্যাপয়েন্টমেন্ট তথ্য", link: "/dashboardAdmin/appointmentInfo", icon: <FaCalendarAlt /> },
  { title: "ভেরিফাই রিকুয়েস্ট", link: "/dashboardAdmin/verification", icon: <FaCheckCircle /> },
  { title: "রিসোর্স", link: "/dashboardAdmin/resources", icon: <FaBookOpen /> },
  { title: "প্রশ্ন ও অভিযোগ", link: "/dashboardAdmin/complaints", icon: <FaComments /> },
  { title: "হেল্প সেকশন", link: "/dashboardAdmin/help", icon: <FaHandsHelping /> },
  { title: "পেআউট", link: "/dashboardAdmin/payout", icon: <FaMoneyCheckAlt /> },
  { title: "প্রোফাইল", link: "/dashboardAdmin/adminProfile", icon: <FaUserShield /> },
  { title: "লগ আউট", link: "/", icon: <FaSignOutAlt /> ,isLogout: true},
];